### PR TITLE
a few updates for deprecated constructs, and a Vagrantfile to run fro…

### PR DESCRIPTION
**Pull request by bbaassssiiee**
…m Mac.

### CODE REVIEW

**Review by arnabsinha4u — CHANGES_REQUESTED** [review]
The current setup does not use Vagrant to deploy the lab on. Its definitely a good feature addition. Can you also modify the readme file to have this as an optional capability?
Like: under the section of Starting up and shutting down the lab, can a section on how to use Vagrant for the same can be added

**Review by arnabsinha4u — CHANGES_REQUESTED** [review]
The current setup does not use Vagrant to deploy the lab on. Its definitely a good feature addition. Can you also modify the readme file to have this as an optional capability?
Like: under the section of Starting up and shutting down the lab, can a section on how to use Vagrant for the same can be added.

**Comment by bbaassssiiee** [comment]
I amended the `README.md`, and tested it again, hence a few small fixes.

**Comment by bbaassssiiee** [comment]
expired.

**Pull request closed without merging**
